#
# Copyright (C) 2015-2017 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

obj-y += fliper/
obj-y += perfmgr/
obj-y += smart/
obj-y += eas_controller/
obj-$(CONFIG_MACH_MT6799) += legacy_controller/
obj-$(CONFIG_MACH_MT6757) += legacy_controller/
obj-$(CONFIG_MACH_MT6759) += legacy_controller/
obj-$(CONFIG_MACH_MT6763) += legacy_controller/
obj-$(CONFIG_MACH_MT6799) += fbc/
obj-$(CONFIG_MACH_MT6759) += fbc/
obj-$(CONFIG_MACH_MT6763) += fbc/

obj-$(CONFIG_MTK_FPSGO) += fpsgo/
