#
# Makefile for all kinds of Fingerprint
#

obj-$(CONFIG_GOODIX_FINGERPRINT) += goodix/
obj-$(CONFIG_FPC_FINGERPRINT) += fpc/
#add OSODEV-1176 by chengwenwu 20171123 start
obj-$(CONFIG_SUNWAVE_TEE_FINGERPRINT) += sunwave_fp_tee/
obj-$(CONFIG_GOODIX_TEE_FINGERPRINT) += goodix_fp_tee/
#add OSODEV-1176 by chengwenwu 20171123 end
