#
# Makefile for all kinds of Fingerprint
#

obj-$(CONFIG_GOODIX_FINGERPRINT) += goodix/
obj-$(CONFIG_BLESTECH_FINGERPRINT) += blestech/
obj-$(CONFIG_BLESTECH_TEE_FINGERPRINT) += blestech_tee/
obj-$(CONFIG_FPC_FINGERPRINT) += fpc/
obj-$(CONFIG_MICROARRAY_FINGERPRINT) += microarray/
obj-$(CONFIG_SUNWAVECORP_FINGERPRINT) += sunwavecorp/
