
# Linux driver folder
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/EKTH3676C/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/

obj-y	+=  elan_ktf.o




